//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cis237Assignment6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beverage
    {
        public string id { get; set; }
        public string name { get; set; }
        public string pack { get; set; }
        public decimal price { get; set; }
        public bool active { get; set; }
    }
}
